name: sbdd

channels:
  - pytorch
  - conda-forge
  - anaconda
  - pyg
  - nvidia

dependencies:
  - python=3.11.8
  - pytorch=2.2.1=*cuda12.1*
  - pytorch-cuda=12.1
  - pytorch-lightning=2.2.1
  - rdkit=2023.09.6
  - openbabel=3.1.1
  - biopython=1.83
  - scipy=1.12.0
  - numpy
  - pymoo
  - pyg=2.5.1
  - pytorch-scatter=2.1.2
  - ProDy=2.4.0
  - wandb=0.16.3
  - pandas=2.2.2
  - imageio=2.37
  - pip=24.0
  - einops=0.8.1
  - gpytorch::gpytorch=1.11
  - rclone
  - pip:
      - posebusters==0.3.1
      - useful_rdkit_utils==0.65
      - fcd==1.2.2
      - webdataset==0.2.86
      - prolif==2.0.3

# After environment instation, please do the following manually: 
# conda activate sbdd
# wget https://github.com/gnina/gnina/releases/download/v1.3.1/
# cp gnina1.3.1 $CONDA_PREFIX/bin/gnina
# chmod +x $CONDA_PREFIX/bin/gnina
# conda env config vars set LD_LIBRARY_PATH=$CONDA_PREFIX/lib